apiVersion: v1
kind: Service
metadata:
 labels:
   name: control-tower
 name: control-tower
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9000
  selector:
    name: control-tower

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: control-tower
  name: control-tower
spec:
  template:
    metadata:
      labels:
        name: control-tower
    spec:
      tolerations:
      - key: "type"
        operator: "Equal"
        value: "gateway"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - gateway
      containers:
      - name: control-tower
        image: vizzuality/control-tower:2.0.4
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "1Gi"
        args:
          - start
        env:
          - name: PORT
            value: "9000"
          - name: LOGGER_TYPE
            value: console
          - name: NODE_ENV
            value: prod
          - name: NODE_PATH
            value: app/src
          - name: BASICAUTH_USERNAME
            value: vizzuality
          - name: CONFIRM_URL_REDIRECT
            value: http://www.globalforestwatch.org
          - name: PUBLIC_URL
            value: http://production-api.globalforestwatch.org
          - name: APP_NAME
            value: "WRI API"
          - name: APP_LOGO
            value: http://www.wri.org/sites/all/themes/wri/images/logo.png
          - name: APP_COLOR
            value: "#f1b319"
          - name: CT_MONGO_URI
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: CT_MONGO_URI
          - name: SESSION_KEY
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: SESSION_KEY
          - name: JWT_SECRET
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: JWT_SECRET
          - name: GFW_TWITTER_CONSUMER_KEY
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: GFW_TWITTER_CONSUMER_KEY
          - name: GFW_TWITTER_CONSUMER_SECRET
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: GFW_TWITTER_CONSUMER_SECRET
          - name: GFW_FACEBOOK_CLIENT_ID
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: GFW_FACEBOOK_CLIENT_ID
          - name: GFW_FACEBOOK_CLIENT_SECRET
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: GFW_FACEBOOK_CLIENT_SECRET
          - name: GFW_GOOGLE_CLIENT_ID
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: GFW_GOOGLE_CLIENT_ID
          - name: GFW_GOOGLE_CLIENT_SECRET
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: GFW_GOOGLE_CLIENT_SECRET
          - name: RW_TWITTER_CONSUMER_KEY
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: RW_TWITTER_CONSUMER_KEY
          - name: RW_TWITTER_CONSUMER_SECRET
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: RW_TWITTER_CONSUMER_SECRET
          - name: RW_FACEBOOK_CLIENT_ID
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: RW_FACEBOOK_CLIENT_ID
          - name: RW_FACEBOOK_CLIENT_SECRET
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: RW_FACEBOOK_CLIENT_SECRET
          - name: RW_GOOGLE_CLIENT_ID
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: RW_GOOGLE_CLIENT_ID
          - name: RW_GOOGLE_CLIENT_SECRET
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: RW_GOOGLE_CLIENT_SECRET
          - name: PREP_TWITTER_CONSUMER_KEY
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: PREP_TWITTER_CONSUMER_KEY
          - name: PREP_TWITTER_CONSUMER_SECRET
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: PREP_TWITTER_CONSUMER_SECRET
          - name: PREP_FACEBOOK_CLIENT_ID
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: PREP_FACEBOOK_CLIENT_ID
          - name: PREP_FACEBOOK_CLIENT_SECRET
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: PREP_FACEBOOK_CLIENT_SECRET
          - name: PREP_GOOGLE_CLIENT_ID
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: PREP_GOOGLE_CLIENT_ID
          - name: PREP_GOOGLE_CLIENT_SECRET
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: PREP_GOOGLE_CLIENT_SECRET
          - name: BASICAUTH_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: BASICAUTH_PASSWORD
          - name: SPARKPOST_KEY
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: SPARKPOST_KEY
          - name: INSTAPUSH_TOKEN
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: INSTAPUSH_TOKEN
          - name: INSTAPUSH_ID
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: INSTAPUSH_ID
          - name: INSTAPUSH_SECRET
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: INSTAPUSH_SECRET
          - name: FASTLY_APIKEY
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: FASTLY_APIKEY
          - name: FASTLY_SERVICEID
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: FASTLY_SERVICEID

        ports:
          - containerPort: 9000
      restartPolicy: Always

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: control-tower
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: control-tower
  minReplicas: 15
  maxReplicas: 100
  targetCPUUtilizationPercentage: 50
