#!/bin/bash


function usage {
  echo -n \
    "Usage: $(basename "$0") COMMAND OPTION[S]
Execute Terraform subcommands.
"
}

set -e

if [[ -n "${WRI_API_AWS_CORE_INFRASTRUCTURE_DEBUG}" ]]; then
  set -x
fi

if [ -z "${ENV}" ]; then
  ENV=dev
fi

if [ -f "/root/.aws/credentials" ]; then
    export AWS_PROFILE=wri-api-${ENV}
    unset AWS_ACCESS_KEY_ID
    unset AWS_SECRET_ACCESS_KEY
    unset AWS_DEFAULT_REGION

    echo "Using enviroment ${ENV} and AWS_PROFILE ${AWS_PROFILE}"
else
  echo "Using enviroment ${ENV} and AWS_ACCESS_KEY_ID"
fi



## select or create the current workspace
#./docker/terraform/workspace

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
  if [ "${1:-}" = "--help" ]; then
    usage
  else

    TERRAFORM_DIR="/usr/local/src/terraform"
    pushd "${TERRAFORM_DIR}"

    case "${1}" in
    fmt)
      terraform fmt -recursive .
      ;;
    plan)
      # Clear stale modules, then re-initialize
      rm -rf .terraform
      # select or create the current workspace
      terraform init \
        -backend-config=vars/backend-${ENV}.tfvars
      terraform plan \
        -var-file="vars/core-${ENV}.tfvars" \
        -out="core.tfplan"
      ;;
    apply)
      terraform apply \
        "core.tfplan"
      ;;
    destroy)
      terraform destroy \
        -var-file="vars/core-${ENV}.tfvars" \
        -auto-approve
      ;;
    *)
      echo "ERROR: I don't have support for that Terraform subcommand!"
      exit 1
      ;;
    esac

    popd
  fi
fi
