apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: {name}
  name: {name}
spec:
  revisionHistoryLimit: 2
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: {name}
    spec:
      restartPolicy: Always
      containers:
      - name: {name}
        image: vizzuality/{name}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "0Mi"
            cpu: "0m"
        args:
          - start
        env:
          - name: APIGATEWAY_URL
            value: "http://35.190.38.44"
          - name: RW_API_URL
            value: "http://35.190.38.44"
          - name: NODE_PATH
            value: app/src
          - name: LOCAL_URL
            value: http://{name}.default.svc.cluster.local:4000
          - name: REDIS_PORT_6379_TCP_ADDR
            value: localhost
          - name: REDIS_PORT_6379_TCP_PORT
            value: "6379"
          - name: ELASTIC_URI
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: ELASTIC_URI
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION
          - name: CARTODB_USER
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CARTODB_USER
        ports:
          - containerPort: 4000
      - name: {name}-cron
        image: vizzuality/{name}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "0Mi"
            cpu: "0m"
        args:
          - startWorker
        env:
          - name: PORT
            value: "4000"
          - name: NODE_ENV
            value: prod
          - name: NODE_PATH
            value: app/src
          - name: LOCAL_URL
            value: http://{name}.default.svc.cluster.local:4000
          - name: REDIS_PORT_6379_TCP_ADDR
            value: localhost
          - name: REDIS_PORT_6379_TCP_PORT
            value: "6379"
          - name: ELASTIC_URI
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: ELASTIC_URI
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION
          - name: STAMPERY_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: STAMPERY_TOKEN
      - name: {name}-redis
        image: redis
        ports:
          - containerPort: 6379
        resources:
          requests:
            memory: "0Mi"
            cpu: "0m"
