apiVersion: v1
kind: Service
metadata:
 labels:
   name: nginx
 name: nginx
 namespace: gateway
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    name: nginx
