apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: elasticsearch-backup
  namespace: core
spec:
  schedule: "35 01 * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: kubecron
              image: vizzuality/kubecron:2.1.5
              imagePullPolicy: Always
              env:
                - name: AWS_BACKUPS_BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      name: backups
                      key: AWS_BACKUPS_BUCKET_NAME
                - name: ES_URI
                    valueFrom:
                      secretKeyRef:
                        name: backups
                        key: ES_URI
                - name: ES_BACKUP_IAM_ROLE
                    valueFrom:
                      secretKeyRef:
                        name: backups
                        key: ES_BACKUP_IAM_ROLE
              args:
                - elasticsearch
          restartPolicy: OnFailure
