apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mongo-backup
  namespace: core
spec:
  schedule: "35 01 * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: kubecron
              image: vizzuality/kubecron:2.1.4
              imagePullPolicy: Always
              env:
                - name: AWS_BACKUPS_BUCKET_URI
                  valueFrom:
                    secretKeyRef:
                      name: backups
                      key: AWS_BACKUPS_BUCKET_URI
                - name: MONGODB_URI
                  valueFrom:
                    secretKeyRef:
                      name: backups
                      key: MONGODB_URI
              args:
                - mongo
          restartPolicy: OnFailure
