apiVersion: v1
kind: Service
metadata:
  labels:
    name: converter
  name: converter
spec:
  ports:
    - port: 3000
  selector:
    name: converter

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: converter
  name: converter
spec:
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: converter
    spec:
      containers:
      - name: converter
        image: vizzuality/converter:1.4.5
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "512Mi"
        args:
          - develop
        env:
          - name: PORT
            value: "3000"
          - name: NODE_ENV
            value: dev
          - name: NODE_PATH
            value: app/src
          - name: NEWRELIC_LICENSE
            value: test
          - name: WORKERS
            value: "1"
          - name: GATEWAY_URL
            value: http://control-tower.default.svc.cluster.local
          - name: CT_URL
            value: http://control-tower.default.svc.cluster.local
          - name: LOCAL_URL
            value: http://converter.default.svc.cluster.local:3000
          - name: GATEWAY_TOKEN
            value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.eUmM_C8WNPBk8EJS3rHo2Zc4wCmYkzyRpRyK8ZzDV2U
          - name: CT_TOKEN
            value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.eUmM_C8WNPBk8EJS3rHo2Zc4wCmYkzyRpRyK8ZzDV2U
          - name: API_VERSION
            value: v1

        ports:
          - containerPort: 3000

      restartPolicy: Always

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: converter
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: converter
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
