apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master
  namespace: core
  labels:
    component: elasticsearch
    role: master
spec:
  clusterIP: None
  selector:
    component: elasticsearch
    role: master
  ports:
    - name: transport
      port: 9300
      protocol: TCP
