# This docker image uses an old version of Terraform, and needs to be updated before it can be used again
version: "3.7"
services:
  terraform:
    image: globalforestwatch/terraform:1.2.2
    volumes:
      - ../../:/usr/local/src
      - $HOME/.aws:/root/.aws:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ENV
      - PROJECT=wri-api
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION=us-east-1
      - DEBUG=1
      - CLOUDFLARE_EMAIL
      - CLOUDFLARE_API_KEY
      - TF_VAR_sparkpost_api_key
    working_dir: /usr/local/src
    entrypoint: infra
