apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-client-v2
  labels:
    type: db-elastic
    component: elasticsearchV2
    role: client
spec:
  replicas: 4
  template:
    metadata:
      labels:
        type: db-elastic
        component: elasticsearchV2
        role: client
    spec:
      initContainers:
      - name: sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      tolerations:
      - key: "type"
        operator: "Equal"
        value: "db-elastic"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - db-elastic
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: role
                operator: In
                values:
                - client
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: es-client
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: quay.io/pires/docker-elasticsearch-kubernetes:5.5.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "4Gi"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "DISCOVERY_SERVICE"
          value: "elasticsearch-discovery-v2"
        - name: "CLUSTER_NAME"
          value: "myesdbV2"
        - name: NODE_MASTER
          value: "false"
        - name: NODE_INGEST
          value: "true"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        - name: "ES_JAVA_OPTS"
          value: "-Xms4g -Xmx4g"
        - name: "ES_PLUGINS_INSTALL"
          value: "https://github.com/NLPchina/elasticsearch-sql/releases/download/5.5.0.0/elasticsearch-sql-5.5.0.1.zip,repository-s3"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: BACKUP_S3_ACCESS_KEY
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: BACKUP_S3_SECRET_KEY
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
          - emptyDir:
              medium: ""
            name: "storage"
