apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data-v2
  labels:
    component: elasticsearchV2
    role: data
spec:
  ports:
  - port: 9300
    name: transport
  clusterIP: None
  selector:
    component: elasticsearchV2
    role: data
