---
# Kong postgres service
kind: Service
apiVersion: v1
metadata:
  name: kong-postgres
spec:
  type: ExternalName
  externalName: kong-database.cgziicsg8pxi.us-east-1.rds.amazonaws.com
---
# Migration Job
apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migrations
spec:
  template:
    metadata:
      name: kong-migrations
    spec:
      containers:
      - name: kong-migrations
        image: kong
        env:
        - name: KONG_NGINX_DAEMON
          value: 'off'
        - name: KONG_DATABASE
          value: postgres
        - name: KONG_PG_DATABASE
          valueFrom:
            secretKeyRef:
              name: kongcreds
              key: postgresdbname
        - name: KONG_PG_USER
          valueFrom:
            secretKeyRef:
              name: kongcreds
              key: username
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kongcreds
              key: password
        - name: KONG_PG_HOST
          value: kong-postgres
        - name: KONG_PG_PORT
          value: "5432"
        command: [ "/bin/sh", "-c", "kong migrations bootstrap", "--vv" ]
      restartPolicy: Never