output "endpoints" {
  value = [
    module.fires_summary_stats_get_fire_alerts_summary_stats_polyname_iso_adm1_code,
    module.fires_summary_stats_get_fire_alerts_summary_stats_polyname_iso.endpoint_gateway_integration,
    module.fires_summary_stats_get_fire_alerts_summary_stats_polyname_iso_adm1_code_adm2_code.endpoint_gateway_integration,
    module.fires_summary_stats_get_glad_alerts_summary_stats_adm_iso_adm1_code.endpoint_gateway_integration,
    module.fires_summary_stats_get_glad_alerts_summary_stats_adm_iso_adm1_code.endpoint_gateway_integration,
    module.fires_summary_stats_get_glad_alerts_summary_stats_adm_iso_adm1_code_adm2_code.endpoint_gateway_integration,
  ]
}