environment                     = "production"
ingress_allow_cidr_block        = "0.0.0.0/0"
dns_prefix                      = "aws-prod"
backups_bucket                  = "wri-api-production-backups"
log_retention_period            = 30
backup_retention_period         = 7
rds_engine_version              = "11.21"
rds_instance_class              = "db.r5.large"
rds_instance_count              = 1
db_instance_class               = "db.r5.large"
db_instance_count               = 3
db_logs_exports                 = ["audit", "profiler"]
eks_version                     = "1.30"
eks_node_release_version        = "1.29.0-20240202"
ebs_csi_addon_version           = "v1.27.0-eksbuild.1"
kube_proxy_addon_version        = "v1.29.15-eksbuild.28"
deploy_canaries                 = true
gateway_node_group_desired_size = 2
hibernate                       = false
aq_bucket_cors_allowed_origin   = "https://www.wri.org"
deploy_sparkpost_templates      = true
gha_role_arn                    = "arn:aws:iam::534760749991:role/wri-api-production-githubactions-role"
apps_node_group_desired_size    = 8
email_recipients                = ["tiago.garcia@vizzuality.com", "solomon.negusse@wri.org"]