apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: elasticsearch
    role: ingest
    type: elasticsearch
  name: es-ingest
  namespace: core
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 3
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      component: elasticsearch
      role: ingest
      type: elasticsearch
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: elasticsearch
        role: ingest
        type: elasticsearch
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - elasticsearch
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - ingest
              topologyKey: kubernetes.io/hostname
      containers:
        - env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: DISCOVERY_SERVICE
              value: elasticsearch-master
            - name: CLUSTER_NAME
              value: document-dataset-storage
            - name: NODE_MASTER
              value: "false"
            - name: NODE_INGEST
              value: "true"
            - name: NODE_DATA
              value: "false"
            - name: HTTP_ENABLE
              value: "true"
            - name: ES_JAVA_OPTS
              value: -Xms2g -Xmx2g
            - name: ES_PLUGINS_INSTALL
              value: https://github.com/NLPchina/elasticsearch-sql/releases/download/5.5.2.0/elasticsearch-sql-5.5.2.0.zip,repository-s3
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: BACKUP_S3_ACCESS_KEY
                  name: elasticsearch
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: BACKUP_S3_SECRET_KEY
                  name: elasticsearch
          image: quay.io/pires/docker-elasticsearch-kubernetes:5.5.2
          imagePullPolicy: Always
          name: es-ingest
          ports:
            - containerPort: 9200
              name: http
              protocol: TCP
            - containerPort: 9300
              name: transport
              protocol: TCP
          resources:
            requests:
              memory: 2Gi
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
                - SYS_RESOURCE
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data
              name: storage
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          image: busybox
          imagePullPolicy: IfNotPresent
          name: sysctl
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: storage
